In [1]:
#importing the dataset

import pandas as pd
train = pd.read_csv('train.csv')
test = pd.read_csv('Test.csv')
x_train = train.iloc[:, 0].values
y_train = train.iloc[:, 1].values
x_test = test.iloc[:, 0].values


In [2]:
print(x_train)
print(y_train)
print(x_test)

['0.png' '1.png' '2.png' ... '48997.png' '48998.png' '48999.png']
[4 9 1 ... 9 3 0]
['49000.png' '49001.png' '49002.png' ... '69997.png' '69998.png'
 '69999.png']


In [3]:
#converting it into matrix form

from keras.utils import np_utils
y_train = np_utils.to_categorical(y_train)

Using TensorFlow backend.


In [4]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [5]:
#converting image data in the form of array 
import numpy as np
from scipy.misc import imread

In [6]:
seed = 128
rng =  np.random.RandomState(seed)

In [7]:
img_name = rng.choice(train.filename)
filepath = "/home/keshav/Downloads/dataset/test/49000.png"
img = imread(filepath, flatten=True)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [8]:
img

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0

In [9]:
#preprocessing training data
temp = []
for img_name in train.filename:
    image_path = "/home/keshav/Downloads/dataset/train/"+img_name
    img = imread(image_path, flatten = True)
    img = img.astype('float32')
    temp.append(img)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """


In [10]:
train_x = np.stack(temp)
train_x /= 255.0
train_x = train_x.reshape(-1,784).astype('float32')

In [11]:
#preprocessing testing data
temp = []
for img_name in test.filename:
    image_path = "/home/keshav/Downloads/dataset/test/"+img_name
    img = imread(image_path, flatten = True)
    img = img.astype('float32')
    temp.append(img)

test_x = np.stack(temp)
test_x /= 255.0
test_x = test_x.reshape(-1,784).astype('float32')

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """


In [12]:
#reshape the data for convolution
train_x_temp = train_x.reshape(-1,28,28,1)


In [13]:

# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D, InputLayer, Reshape, Dropout, Activation
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

# Initialising the CNN
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(25, (5,5), input_shape = (28,28,1), activation = 'relu'))

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(25, (5,5), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(output_dim = 50, activation = 'relu'))
classifier.add(Dense(output_dim = 10, input_dim = 50, activation = 'softmax'))

# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:26: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=50)`
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:27: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", input_dim=50, units=10)`


In [14]:
# fitting
trained_model_conv = classifier.fit(train_x_temp, y_train, nb_epoch = 5, batch_size = 128 )

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/5
49000/49000 [==============================] - 30s 613us/step - loss: 0.3226 - acc: 0.9034
Epoch 2/5
49000/49000 [==============================] - 31s 634us/step - loss: 0.0831 - acc: 0.9750
Epoch 3/5
49000/49000 [==============================] - 31s 631us/step - loss: 0.0593 - acc: 0.9819
Epoch 4/5
49000/49000 [==============================] - 30s 609us/step - loss: 0.0451 - acc: 0.9859
Epoch 5/5
49000/49000 [==============================] - 30s 608us/step - loss: 0.0365 - acc: 0.9886


In [27]:
#predicting the result
import cv2
final = []
for img_name in test.filename:
    test_image = cv2.imread("/home/keshav/Downloads/dataset/test/"+img_name)
    test_image = cv2.resize(test_image,(28,28))
    test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
    test_image = test_image.reshape((-1,28,28,1))
    result = classifier.predict(test_image)
    final.append(result)
print(final)

[array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32), array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32), array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32), array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32), array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32), array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32), array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32), array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 1.299915e-37]], dtype=float32), array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32), array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32), array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32), array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32), array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32), array([[0., 0., 0., 0., 0

In [ ]:
#we can also predict handwritten digits, by simply showing handwritten digit in front of webcam

import cv2
print("Press 'c' to capture the photo")
print("press 'q' to exit")
#to start the webcam or external web camera
capture = cv2.VideoCapture(0)

#camera will switch on
while capture.isOpened():
		
	status,frame = capture.read()
	cv2.rectangle(frame,(100,100),(250,250),(0,0,255),2)	
	cv2.imshow("frame1",frame)
	if cv2.waitKey(1) & 0xFF == ord("c")  :

	#saving and copying the part of image into another image roi(region of interest)
		roi = frame[100:250 , 100 :250]
	#coordinates of the rectangle form are (100,100) and (250,250)	
	#saving the image
		cv2.imwrite("predict_image.png",roi)	
	
		capture.release()
		cv2.waitKey(0)

	#exit the loop
	if cv2.waitKey(1) & 0xFF == ord("q")  : 
		break

test_image = cv2.imread("/home/keshav/Downloads/dataset/predict_image.png")
test_image = cv2.resize(test_image,(28,28))
test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
test_image = test_image.reshape((-1,28,28,1))
result = classifier.predict(test_image)
print(result)

Press 'c' to capture the photo
press 'q' to exit
